Repo Clean up (#48)
* fix broadcasting scripts

* print actions, calldata and new addresses

* natspec

* fix husky pre commit

* refactor

* multisig test fix

* timelock test fix

* doc fix

* introduces addresses path and caller in Proposal constructor

* refactor to not need PK on run function

* clean test suite

* BravoPostProposalCheck

* BravoPostProposalCheck multiple > single proposal

* simplify MultisigPostProposalCheck

* simplify TimelockPostProposalCheck

* clean Proposal.sol

* unused variables

* make CI fails on lint errors

* error on non used import

* yml indentation

* organize imports

* delete script folder

* configure testnet safe deployment

* deploy timelock to sepolia testnet

* remove internal function arguments

* remove logs

* log changed addresses and default debug to true

* print actions

* docs checkpoint

* unused imports

* multisig proposal guide

* fix tests

* timelock proposal doc

* integration testt docs + governor bravo

* delete .env.example

* add prettier back to pre-commit husky

* prettier

* foundry.toml

* markdown sections

* checkpoint

* bravo deploy

* print addresses on Addresses.sol

* Initialize bravo + accept ownership

* diagram

* review changes

* bravo proposol markdown

* review changes

* fix env

* remove build step from CI

* apply lint suggestions

* compile

* receive function

* update file access permission

* install ts-node

* add forge build to type-check tests on CI

* update artifact path for local contract deployment in type check

* review changes

* Duplication actions check

* add ETA to doc

* remove encode and compare bytes directly

* add keccak256 back

* remove encode.ts logs

---------

Co-authored-by: prateek <prateekgupta105@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,29 +12,36 @@ on:
 
 jobs:
     lint:
-        runs-on: "ubuntu-latest"
-        steps:
-            - name: "Check out the repo"
-              uses: "actions/checkout@v3"
-              with:
-                  submodules: "recursive"
+     runs-on: ubuntu-latest
+     steps:
+       - name: "Check out the repo"
+         uses: actions/checkout@v3
+         with:
+           submodules: recursive
+       - name: "Install Node.js"
+         uses: actions/setup-node@v3
+         with:
+           node-version: lts/*
 
-            - name: "Install Node.js"
-              uses: "actions/setup-node@v3"
-              with:
-                  node-version: "lts/*"
+       - name: "Install the Node.js dependencies"
+         run: npm install
 
-            - name: "Install the Node.js dependencies"
-              run: "npm install"
-
-            - name: "Lint the contracts"
-              run: "npm run lint"
-
-            - name: "Add lint summary"
-              run: |
-                  echo "## Lint result" >> $GITHUB_STEP_SUMMARY
-                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
-
+       - name: Run linter and check for errors
+         id: lint
+         run: |
+           LINT_OUTCOME=$(npm run lint 2>&1 || true) # Prevent the step from failing immediately
+           echo "$LINT_OUTCOME"
+           echo "LINT_OUTCOME<<EOF" >> $GITHUB_ENV
+           echo "$LINT_OUTCOME" >> $GITHUB_ENV
+           echo "EOF" >> $GITHUB_ENV
+           if echo "$LINT_OUTCOME" | grep -q " error "; then
+             echo "## Lint result" >> $GITHUB_STEP_SUMMARY
+             echo "❌ Failed due to errors" >> $GITHUB_STEP_SUMMARY
+             exit 1
+           else
+             echo "## Lint result" >> $GITHUB_STEP_SUMMARY
+             echo "✅ Passed or warnings found" >> $GITHUB_STEP_SUMMARY
+           fi
     proposal-simulator-test:
         runs-on: "ubuntu-latest"
         steps:
@@ -88,7 +95,10 @@ jobs:
                   node-version: "lts/*"
 
             - name: "Install the Node.js dependencies"
-              run: "cd typescript/ && npm install && cd ../"
+              run: "cd typescript/ && npm install && cd ../ && npm install ts-node"
+
+            - name: "Build the contracts and print their size"
+              run: "forge build --sizes"
 
             - name: "Run typecheck tests"
               run: "forge test --mc TypeCheck --ffi --fork-url sepolia"
